name: Compute version

inputs:
  prefix:
    type: string
    required: true
  paths:
    type: string
    required: false
    description: A space-separated list of paths to monitor for changes. If not provided, the entire repository is monitored.
  main_branch:
    type: string
    required: false
    description: The main branch to compare against. Defaults to the default branch of the repository.

outputs:
  previous_version:
    description: The previous version
    value: ${{ steps.semantic-version.outputs.previous_version }}
  version:
    description: The computed version
    value: ${{ steps.semantic-version.outputs.version }}
  version_tag:
    description: The computed version tag
    value: ${{ steps.semantic-version.outputs.version_tag }}
  needs_bump:
    description: Whether to bump the version
    value: ${{ steps.check_bump.outputs.needs_bump }}
  suffix:
    description: The computed suffix
    value: ${{ steps.set_suffix.outputs.suffix }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get next version
      uses: PaulHatch/semantic-version@v5.4.0
      id: semantic-version
      with:
        tag_prefix: ${{ inputs.prefix }}
        major_pattern: "feat!"
        minor_pattern: "feat"
        bump_each_commit: true
        bump_each_commit_patch_pattern: "fix"
        version_format: "${major}.${minor}.${patch}"
        change_path: ${{ inputs.paths }}

    - name: Set suffix
      id: set_suffix
      if: ${{ github.event_name == 'pull_request' && steps.semantic-version.outputs.changed == 'true' }}
      run: echo "suffix=-pr.${{ github.event.pull_request.number }}.${{ github.run_number }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check if bump is needed
      id: check_bump_version
      run: |
        if [[ "${{ steps.set_suffix.outputs.suffix }}" ]] || [[ "${{ steps.semantic-version.outputs.version }}" != "${{ steps.semantic-version.outputs.previous_version }}" ]]; then
          echo "needs_bump=true" >> $GITHUB_OUTPUT
          echo "Bumping version is required: version change or PR build detected"
        else
          echo "needs_bump=false" >> $GITHUB_OUTPUT
          echo "Bumping version not needed: same version and not a PR build"
        fi
      shell: bash

    - name: Outputs
      run: |
        echo "Previous Version: ${{ steps.semantic-version.outputs.previous_version }}"
        echo "Version: ${{ steps.semantic-version.outputs.version }}"
        echo "Version Tag: ${{ steps.semantic-version.outputs.version_tag }}"
        echo "Suffix: ${{ steps.set_suffix.outputs.suffix }}"
        echo "Needs Bump: ${{ steps.check_bump_version.outputs.needs_bump }}"
        echo "Increment: ${{ steps.semantic-version.outputs.increment }}"
        echo "Is Tagged: ${{ steps.semantic-version.outputs.is_tagged }}"
      shell: bash