name: Build and Test .NET Project

inputs:
  path-project:
    description: "Path to the dotnet project"
    required: true
    type: string
  path-test:
    description: "Path to the dotnet test project"
    required: false
    default: ""
    type: string
  dotnet-version:
    description: "The version of .NET to use"
    type: string
    required: true
    default: "8.0.x"

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.path-project }}
      shell: bash
    - name: Build
      run: dotnet build ${{ inputs.path-project }} --no-restore
      shell: bash
    - name: Test
      if: inputs.path-test != ''
      run: dotnet test --verbosity normal  ${{ inputs.path-test }}
      shell: bash